// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StarTEDSystemDB.Entities;

[Index("CourseId", Name = "IX_CourseID")]
[Index("ProgramId", Name = "IX_ProgramID")]
[Index("ProgramId", "CourseId", Name = "UN_dbo.ProgramCourses_ProgramIDCourseID", IsUnique = true)]
public partial class ProgramCourse
{
    [Key]
    [Column("ProgramCourseID")]
    public int ProgramCourseId { get; set; }

    [Column("ProgramID")]
    public int ProgramId { get; set; }

    [Required]
    [Column("CourseID")]
    [StringLength(7)]
    [Unicode(false)]
    public string CourseId { get; set; }

    public bool Required { get; set; }

    [StringLength(50)]
    public string Comments { get; set; }

    public int SectionLimit { get; set; }

    public bool Active { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("ProgramCourses")]
    public virtual Course Course { get; set; }

    [ForeignKey("ProgramId")]
    [InverseProperty("ProgramCourses")]
    public virtual Program Program { get; set; }
}