// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using StarTEDSystemDB.Entities;
using Microsoft.EntityFrameworkCore;

namespace StarTEDSystemDB.DAL;

internal partial class StarTEDContext : DbContext
{
    //public StarTEDContext()
    //{
    //}

    public StarTEDContext(DbContextOptions<StarTEDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Program> Programs { get; set; }

    public virtual DbSet<ProgramCourse> ProgramCourses { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=StarTED;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("PK_dbo.Courses");
        });

        modelBuilder.Entity<Program>(entity =>
        {
            entity.HasKey(e => e.ProgramId).HasName("PK_dbo.Programs");
        });

        modelBuilder.Entity<ProgramCourse>(entity =>
        {
            entity.HasKey(e => e.ProgramCourseId).HasName("PK_dbo.ProgramCourses");

            entity.HasOne(d => d.Course).WithMany(p => p.ProgramCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.ProgramCourses_dbo.Courses_CourseID");

            entity.HasOne(d => d.Program).WithMany(p => p.ProgramCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.ProgramCourses_dbo.Programs_ProgramID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}